---
- name: Configure 3teir on AWS
  hosts: jumpbox
  gather_facts: true
  roles:
   - { role: ../../roles/osp.facts }
  tags:
    - osp.facts

- name: Setup RedHat Repositories
  hosts: all
  become: yes
  roles:
   - { role: ../../roles/repo-config }
  tags:
    - setup-repos

- name: Setup HAProxy
  hosts: frontends
  become: yes
  roles:
   - { role: ../../roles/haproxy }
  tags:
    - setup-haproxy

- name: Setup HTTP and Tomcat
  hosts: apps
  become: yes
  # gather_facts: false
  roles:
   - { role: ../../roles/http-tomcat }
  tags:
    - setup-tomcat

- name: Setup application1 
  hosts: apps
  become: yes
  roles:
   - { role: ../../roles/application1 }

- name: Setup application2 
  hosts: apps
  become: yes
  roles:
   - { role: ../../roles/application2 }

- name: Setup postgresql
  hosts: appdbs
  become: yes
  roles:
   - { role: ../../roles/postgresql }
  tags:
    - setup-postgresql