---
- name: install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest
  tags:
    - setup-haproxy

- name: enable {{ payload }} at boot
  service:
    name: "{{ payload }}"
    enabled: yes
  tags:
    - setup-haproxy

- name: configure haproxy to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  tags:
    - setup-haproxy
    
- name: start {{ payload }}
  service:
    name: "{{ payload }}"
    state: restarted
  tags:
    - setup-haproxy