---
# tasks file for check
- name: OpenStack servers
  os_server_facts:
    cloud: osp_cloud
    server: 'frontend'
  tags:
    - smokeTest

# - name: Test
#   debug: var=item
#   with_items: "{{openstack_servers|json_query('accessIPv4')}}"
#   tags:
#     - smokeTest

- name: Curl website
  uri:
    url: "http://{{item.accessIPv4}}"
    return_content: yes
  with_items:
    - "{{ openstack_servers}}"
  register: webpage  
  tags:
    - smokeTest

- name: Fail if Status Code is not 200
  fail:
  when: item.status != 200
  with_items: 
  - "{{ webpage.results}}"
  tags:
  - smokeTest